#!/bin/bash
docker build --build-arg VERSION=${DOCKER_TAG} \
             --build-arg OS="${OSTYPE}" \
             --build-arg MACHINE=$(uname --machine) \
             -f ${DOCKERFILE_PATH} \
             -t ${IMAGE_NAME} .
